version: '2.4'

services:
  app:
    image: nmid
    build: .    
    container_name: nmid
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      DJANGO_SECRET_KEY: "local secret key"
      DJANGO_MANAGEPY_MIGRATE: "on"
      DJANGO_DEBUG: "True"
    entrypoint: /app/docker-entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    container_name: nmid-postgres
    image: postgres:9.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: nmid
      POSTGRES_PASSWORD: postgres
    volumes:
      - nmid-db-data:/var/lib/postgresql/data
    ports:
      - 32001:5432

volumes:
  nmid-db-data:
