# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
    ]
