# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_auto_20160915_0940"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="template",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
