# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20160930_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blob',
            name='page',
        ),
    ]
