# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_blob_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(default='pages/default.html', max_length=255),
        ),
    ]
