# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 17:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100, null=True)),
                ("city", models.CharField(max_length=50, null=True)),
                ("state", models.CharField(max_length=50, null=True)),
                ("zip_code", models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=10, null=True)),
                ("first_name", models.CharField(max_length=20, null=True)),
                ("middle_name", models.CharField(max_length=20, null=True)),
                ("last_name", models.CharField(max_length=20, null=True)),
                ("suffix", models.CharField(max_length=10, null=True)),
                ("business_phone", models.CharField(max_length=20, null=True)),
                ("home_phone", models.CharField(max_length=20, null=True)),
                ("date_added", models.DateTimeField(null=True)),
                ("email", models.CharField(max_length=50, null=True)),
                ("date_updated", models.DateTimeField(null=True)),
                ("qual_candidate_id", models.IntegerField(null=True)),
                ("deceased", models.BooleanField()),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camp_fin.Address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_date", models.DateField()),
                ("date_added", models.DateTimeField()),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("middle_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("company_name", models.CharField(max_length=255, null=True)),
                ("occupation", models.CharField(max_length=255, null=True)),
                ("contribution_type", models.CharField(max_length=100)),
                ("amount", models.FloatField()),
                ("memo", models.TextField(null=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camp_fin.Address",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camp_fin.Candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expenditure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expended_date", models.DateField()),
                ("date_added", models.DateTimeField()),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("middle_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("company_name", models.CharField(max_length=255, null=True)),
                ("occupation", models.CharField(max_length=255, null=True)),
                ("amount", models.FloatField()),
                ("memo", models.TextField(null=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camp_fin.Address",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camp_fin.Candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Filing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opening_balance", models.FloatField()),
                ("closing_balance", models.FloatField()),
                ("filing_date", models.DateField()),
                ("received_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PAC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("acronym", models.CharField(max_length=15, null=True)),
                ("business_phone", models.CharField(max_length=20, null=True)),
                ("home_phone", models.CharField(max_length=20, null=True)),
                ("email", models.CharField(max_length=50, null=True)),
                ("date_added", models.DateTimeField()),
                ("date_updated", models.DateTimeField(null=True)),
                ("bank", models.CharField(max_length=100, null=True)),
                ("bank_phone", models.CharField(max_length=50, null=True)),
                ("fax_number", models.CharField(max_length=50, null=True)),
                ("initial_balance", models.FloatField(null=True)),
                ("initial_balance_from_self", models.NullBooleanField()),
                ("initial_debt", models.FloatField(null=True)),
                ("initial_debt_from_self", models.NullBooleanField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="camp_fin.Address",
                    ),
                ),
                (
                    "bank_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_address",
                        to="camp_fin.Address",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camp_fin.Contact",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camp_fin.Entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Treasurer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pac",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="camp_fin.Status"
            ),
        ),
        migrations.AddField(
            model_name="pac",
            name="treasurer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="camp_fin.Treasurer"
            ),
        ),
        migrations.AddField(
            model_name="expenditure",
            name="filing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="camp_fin.Filing"
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="filing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="camp_fin.Filing"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="camp_fin.Contact",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="camp_fin.Entity"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="camp_fin.Status",
            ),
        ),
    ]
