# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0002_auto_20160817_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Address'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Contact'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='entity',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Entity'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Status'),
        ),
    ]
