# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0004_auto_20160817_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olddb_id', models.IntegerField(null=True)),
                ('date_added', models.DateTimeField()),
                ('last_updated', models.DateTimeField(null=True)),
                ('primary_election_winner_status', models.IntegerField()),
                ('general_election_winner_status', models.IntegerField()),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('bank_phone', models.CharField(max_length=50, null=True)),
                ('committee_name', models.CharField(max_length=100, null=True)),
                ('committee_phone_1', models.CharField(max_length=25, null=True)),
                ('committee_phone_2', models.CharField(max_length=25, null=True)),
                ('committee_fax_number', models.CharField(max_length=25, null=True)),
                ('committee_email', models.CharField(max_length=50, null=True)),
                ('initial_balance', models.FloatField(null=True)),
                ('initial_balance_from_self', models.NullBooleanField()),
                ('initial_debt', models.FloatField(null=True)),
                ('initial_debt_from_self', models.NullBooleanField()),
                ('qual_campaign_id', models.IntegerField(null=True)),
                ('biannual', models.NullBooleanField()),
                ('bank_address', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_bank_address', to='camp_fin.Address')),
                ('candidate', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Candidate')),
                ('committee_address', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee_address', to='camp_fin.Address')),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FilingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('olddb_id', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('allow_no_activity', models.BooleanField()),
                ('exclude_from_cascading', models.BooleanField()),
                ('supplemental_init_date', models.DateTimeField(null=True)),
                ('initial_date', models.DateField()),
                ('email_sent_status', models.IntegerField()),
                ('reminder_sent_status', models.IntegerField()),
                ('reminder_sent_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RegularFilingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('received_date', models.DateTimeField()),
                ('date_added', models.DateTimeField()),
                ('check_number', models.CharField(max_length=50, null=True)),
                ('memo', models.TextField(null=True)),
                ('description', models.CharField(max_length=75, null=True)),
                ('olddb_id', models.IntegerField()),
                ('name_prefix', models.CharField(max_length=5, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('suffix', models.CharField(max_length=15, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=5, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('from_file_id', models.IntegerField(null=True)),
                ('contact_type_other', models.CharField(max_length=5, null=True)),
                ('occupation', models.CharField(max_length=255, null=True)),
                ('expenditure_for_certified_candidate', models.NullBooleanField()),
                ('candidate', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Candidate')),
                ('contact', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Contact')),
                ('contact_type', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.ContactType')),
                ('county', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.County')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('contribution', models.BooleanField()),
                ('anonymous', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='filing',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='address',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='filing',
        ),
        migrations.RenameField(
            model_name='filing',
            old_name='received_date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='pac',
            old_name='bank',
            new_name='bank_name',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='filing_date',
        ),
        migrations.AddField(
            model_name='filing',
            name='date_closed',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 29, 18, 49, 13, 779538, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='date_last_amended',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='edited',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='final',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='no_activity',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='olddb_campaign_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='olddb_ethics_report_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='olddb_profile_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='pdf_report',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='regenerate',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='filing',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='supplement_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='total_contributions',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='total_debt_carried_forward',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='total_debt_paid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='total_expenditures',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='total_inkind',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='total_loans',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='total_loans_forgiven',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='total_supplemental_contributions',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='total_unpaid_debts',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pac',
            name='address',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='camp_fin.Address'),
        ),
        migrations.AlterField(
            model_name='pac',
            name='bank_address',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pac_bank_address', to='camp_fin.Address'),
        ),
        migrations.AlterField(
            model_name='pac',
            name='contact',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Contact'),
        ),
        migrations.AlterField(
            model_name='pac',
            name='status',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Status'),
        ),
        migrations.AlterField(
            model_name='pac',
            name='treasurer',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Treasurer'),
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='Expenditure',
        ),
        migrations.AddField(
            model_name='transaction',
            name='filing',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Filing'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Status'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.TransactionType'),
        ),
        migrations.AddField(
            model_name='office',
            name='office_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.OfficeType'),
        ),
        migrations.AddField(
            model_name='filingperiod',
            name='filing_period_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.FilingType'),
        ),
        migrations.AddField(
            model_name='filingperiod',
            name='regular_filing_period',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.RegularFilingPeriod'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='county',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.County'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='district',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.District'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='division',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Division'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='election_season',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.ElectionSeason'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='from_campaign',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='office',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Office'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='political_party',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.PoliticalParty'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Status'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='treasurer',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Treasurer'),
        ),
        migrations.AddField(
            model_name='filing',
            name='campaign',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Campaign'),
        ),
        migrations.AddField(
            model_name='filing',
            name='filing_period',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.FilingPeriod'),
            preserve_default=False,
        ),
    ]
