# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0007_auto_20160829_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='olddb_ethics_report_id',
            field=models.IntegerField(null=True),
        ),
    ]
