# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0010_auto_20160829_1321"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filingperiod",
            name="reminder_sent_date",
        ),
    ]
