# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 20:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0011_remove_filingperiod_reminder_sent_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="candidate",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="camp_fin.Candidate",
            ),
        ),
    ]
