# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0015_auto_20160829_1442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="general_election_winner_status",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="primary_election_winner_status",
            field=models.IntegerField(null=True),
        ),
    ]
