# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0017_auto_20160829_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='division',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Division'),
        ),
    ]
