# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0019_auto_20160829_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='status',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='office',
            name='office_type',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.OfficeType'),
        ),
    ]
