# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0025_auto_20160902_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.CampaignStatus'),
        ),
    ]
