# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0026_auto_20160906_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='name',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='office',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Office'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Status'),
            preserve_default=False,
        ),
    ]
