# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0031_auto_20160906_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='check_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
