# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0034_auto_20160906_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialevent",
            name="sponsors",
            field=models.TextField(null=True),
        ),
    ]
