# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0037_auto_20160908_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
