# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0041_auto_20160909_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='full_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='full_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
