# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0042_auto_20160909_0856"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="postal_code",
            field=models.CharField(default="", max_length=2),
            preserve_default=False,
        ),
    ]
