# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0043_state_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="postal_code",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
