# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0046_auto_20160913_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='received_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
