# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0047_auto_20160915_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='edited',
            field=models.CharField(max_length=3),
        ),
    ]
