# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0050_auto_20160923_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
