# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0051_auto_20161004_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='check_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
