# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0052_auto_20161104_1045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
