# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 15:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0054_auto_20170412_0912"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="candidate",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="camp_fin.Candidate",
            ),
        ),
    ]
