# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0056_auto_20171211_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='county',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.County'),
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together=set([('district', 'division', 'office_type', 'county', 'office', 'election_season')]),
        ),
    ]
