# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0057_auto_20171212_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='county',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.County'),
        ),
        migrations.AlterField(
            model_name='race',
            name='district',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.District'),
        ),
        migrations.AlterField(
            model_name='race',
            name='division',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Division'),
        ),
        migrations.AlterField(
            model_name='race',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.RaceGroup'),
        ),
        migrations.AlterField(
            model_name='race',
            name='office_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.OfficeType'),
        ),
        migrations.AlterField(
            model_name='race',
            name='winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Campaign'),
        ),
    ]
