# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-04 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0058_auto_20180103_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbyist',
            name='slug',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lobbyist',
            name='contact',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.Contact'),
        ),
        migrations.AlterField(
            model_name='lobbyist',
            name='filing_period',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp_fin.LobbyistFilingPeriod'),
        ),
    ]
