# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-08 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0059_campaign_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                ("title", models.CharField(max_length=500)),
                (
                    "candidate",
                    models.ManyToManyField(blank=True, to="camp_fin.Candidate"),
                ),
                ("race", models.ManyToManyField(blank=True, to="camp_fin.Race")),
            ],
            options={
                "verbose_name_plural": "stories",
            },
        ),
    ]
