# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-11 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0060_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='note',
        ),
    ]
