# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-07 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0061_remove_campaign_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='dropouts',
            field=models.ManyToManyField(blank=True, null=True, related_name='dropout_race', to='camp_fin.Campaign'),
        ),
    ]
