# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0064_auto_20180308_1154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="race_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("dropout", "Dropped out"),
                    ("lost_primary", "Lost primary"),
                ],
                default="active",
                max_length=25,
                null=True,
            ),
        ),
    ]
