# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0065_auto_20180412_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filingperiod',
            name='reminder_sent_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
