# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0067_auto_20180412_0922"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="total_contributions",
            field=models.FloatField(null=True),
        ),
    ]
