# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0068_race_total_contributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='regenerate',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
