# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('camp_fin', '0070_auto_20180920_1242'), ('camp_fin', '0071_auto_20180920_1244'), ('camp_fin', '0072_auto_20180920_1246'), ('camp_fin', '0073_auto_20180920_1248')]

    dependencies = [
        ('camp_fin', '0069_auto_20180518_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='closing_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='filing',
            name='opening_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='filing',
            name='total_contributions',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='filing',
            name='total_expenditures',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='filing',
            name='date_closed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='filing',
            name='final',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='filing',
            name='no_activity',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='filing',
            name='edited',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
