# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0069_auto_20180518_1331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filing",
            name="closing_balance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="filing",
            name="opening_balance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="filing",
            name="total_contributions",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="filing",
            name="total_expenditures",
            field=models.FloatField(null=True),
        ),
    ]
