# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0070_auto_20180920_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='date_closed',
            field=models.DateTimeField(null=True),
        ),
    ]
