# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-02 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0071_auto_20181102_1251"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lobbyistreport",
            name="entertainment_expenses",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="lobbyistreport",
            name="gift_expenses",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="lobbyistreport",
            name="meal_beverage_expenses",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="lobbyistreport",
            name="other_expenses",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="lobbyistreport",
            name="special_event_expenses",
            field=models.FloatField(null=True),
        ),
    ]
