# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0071_auto_20180920_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='final',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='filing',
            name='no_activity',
            field=models.NullBooleanField(),
        ),
    ]
