# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-02 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0072_auto_20181102_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobbyistreport',
            name='expenditures',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lobbyistreport',
            name='political_contributions',
            field=models.FloatField(null=True),
        ),
    ]
