# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0072_auto_20180920_1246"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filing",
            name="edited",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
