# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-30 21:04
from __future__ import unicode_literals

import os

from django.db import migrations, models

sql_script = os.path.join(
    os.path.dirname(__file__), "..", "..", "scripts", "sql", "drop_triggers.sql"
)

with open(sql_script, "r") as script:
    drop_triggers = script.read()


class Migration(migrations.Migration):
    dependencies = [
        ("camp_fin", "0075_fix_date_added_default"),
    ]

    operations = [
        migrations.RunSQL(drop_triggers, reverse_sql="SELECT 1"),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="bank_phone",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="committee_email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="business_phone",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="home_phone",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="middle_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="middle_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="check_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lobbyist",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lobbyist",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lobbyist",
            name="middle_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lobbyistreport",
            name="pdf_report",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pac",
            name="bank_phone",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pac",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pac",
            name="fax_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="specialevent",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="treasurer",
            name="alt_phone",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="treasurer",
            name="business_phone",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="treasurer",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="treasurer",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="treasurer",
            name="middle_name",
            field=models.CharField(max_length=255, null=True),
        ),
        # This is hacky but necessary to making this migration reversible
        migrations.RunSQL("SELECT 1", reverse_sql=drop_triggers),
    ]
