# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-12-13 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0077_auto_20231212_1005"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="redact",
            field=models.BooleanField(default=False),
        ),
    ]
