# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-12-18 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0078_transaction_redact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="redact",
            field=models.NullBooleanField(default=False),
        ),
    ]
