# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-12-21 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0079_auto_20231218_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
