# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-12-21 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0080_auto_20231221_1031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="politicalparty",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
