# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-18 13:37
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0081_auto_20231221_1042"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filingperiod",
            name="filing_date",
        ),
        migrations.AddField(
            model_name="filing",
            name="filed_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filingperiod",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
