# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-01-18 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0081_auto_20231221_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='user_id',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
