# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-18 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0082_auto_20240418_0737"),
    ]

    operations = [
        migrations.AddField(
            model_name="filing",
            name="report_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="filing",
            name="report_version_id",
            field=models.IntegerField(null=True),
        ),
    ]
