# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-18 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0083_auto_20240418_0905"),
    ]

    operations = [
        migrations.RunSQL(
            "create unique index camp_fin_filing_report_id_idx on camp_fin_filing (report_id) where final = True",
            reverse_sql="drop index camp_fin_filing_report_id_idx",
        ),
    ]
