# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-24 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0084_auto_20240418_1048"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="sos_link",
            field=models.URLField(default="https://google.com"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pac",
            name="sos_link",
            field=models.URLField(default="https://google.com"),
            preserve_default=False,
        ),
    ]
