# Generated by Django 3.2.25 on 2024-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0084_auto_20240418_1048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="biannual",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="initial_balance_from_self",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="initial_debt_from_self",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="filing",
            name="final",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="filing",
            name="no_activity",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="lobbyistfilingperiod",
            name="allow_statement_of_no_activity",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="lobbyistregistration",
            name="is_registered",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="pac",
            name="initial_balance_from_self",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="pac",
            name="initial_debt_from_self",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expenditure_for_certified_candidate",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="redact",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
