# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-24 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0085_auto_20240424_1218"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="sos_link",
        ),
        migrations.AddField(
            model_name="campaign",
            name="sos_link",
            field=models.URLField(default="https://google.com"),
            preserve_default=False,
        ),
    ]
