# Generated by Django 3.2.25 on 2024-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_fin', '0090_alter_address_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='prefix',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='suffix',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prefix',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='suffix',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='zipcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lobbyist',
            name='prefix',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lobbyist',
            name='suffix',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialevent',
            name='zipcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='zipcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treasurer',
            name='prefix',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treasurer',
            name='suffix',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
