# Generated by Django 3.2.25 on 2025-01-21 14:16
from django.core.management import call_command
from django.db import connection, migrations, models, transaction


@transaction.atomic
def drop_triggers(apps, schema_editor):
    with connection.cursor() as c:
        for trigger_name, table_name in (
            ("candidate_search_update", "camp_fin_candidate"),
            ("lobbyist_search_update", "camp_fin_lobbyist"),
            ("lobbyisttransaction_search_update", "camp_fin_lobbyisttransaction"),
            ("organization_search_update", "camp_fin_organization"),
            ("pac_search_update", "camp_fin_pac"),
            ("add_anonymous_transactions", "camp_fin_transaction"),
            ("transaction_search_update", "camp_fin_transaction"),
            ("treasurer_search_update", "camp_fin_treasurer"),
        ):
            c.execute(
                "drop trigger if exists {0} on {1}".format(trigger_name, table_name)
            )


def add_triggers(apps, schema_editor):
    call_command("make_search_index")


class Migration(migrations.Migration):
    dependencies = [
        ("camp_fin", "0092_alter_campaignstatus_description"),
    ]

    operations = [
        migrations.RunPython(drop_triggers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="address",
            name="zipcode",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="bank_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaignstatus",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="occupation",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contacttype",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="filing",
            name="pdf_report",
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name="lobbyist",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lobbyistbundlingdisclosure",
            name="destinatary_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lobbyistbundlingdisclosurecontributor",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lobbyistfilingperiod",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lobbyistspecialevent",
            name="event_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lobbyistspecialevent",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lobbyisttransactiontype",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="office",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pac",
            name="bank_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pac",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="specialevent",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="check_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(add_triggers, migrations.RunPython.noop),
    ]
