# Generated by Django 3.2.25 on 2025-01-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp_fin", "0092_alter_campaignstatus_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="zipcode",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="bank_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaignstatus",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="occupation",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contacttype",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="filing",
            name="pdf_report",
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name="lobbyist",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lobbyistbundlingdisclosure",
            name="destinatary_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lobbyistbundlingdisclosurecontributor",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lobbyistfilingperiod",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lobbyistspecialevent",
            name="event_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lobbyistspecialevent",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lobbyisttransactiontype",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="office",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pac",
            name="bank_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pac",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="specialevent",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="check_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
