DROP TABLE IF EXISTS :table_name;

CREATE TABLE :table_name (
	"OrgID" TEXT,
	"Expenditure Amount" TEXT,
	"Expenditure Date" DATE,
	"Payee Last Name" TEXT,
	"Payee First Name" TEXT,
	"Payee Middle Name" TEXT,
	"Payee Prefix" TEXT,
	"Payee Suffix" TEXT,
	"Payee Address 1" TEXT,
	"Payee Address 2" TEXT,
	"Payee City" TEXT,
	"Payee State" TEXT,
	"Payee Zip Code" TEXT,
	"Description" TEXT,
	"Expenditure ID" TEXT,
	"Filed Date" DATE,
	"Election" TEXT,
	"Report Name" TEXT,
	"Start of Period" DATE,
	"End of Period" DATE,
	"Purpose" TEXT,
	"Expenditure Type" TEXT,
	"Reason" TEXT,
	"Stance" TEXT,
	"Report Entity Type" TEXT,
	"Committee Name" TEXT,
	"Candidate Last Name" TEXT,
	"Candidate First Name" TEXT,
	"Candidate Middle Name" TEXT,
	"Candidate Prefix" TEXT,
	"Candidate Suffix" TEXT,
	"Amended" TEXT
);
