DROP TABLE IF EXISTS :table_name;

CREATE TABLE :table_name (
	"OrgID" TEXT,
	"Transaction Amount" TEXT,
	"Transaction Date" DATE,
	"Last Name" TEXT,
	"First Name" TEXT,
	"Middle Name" TEXT,
	"Prefix" TEXT,
	"Suffix" TEXT,
	"Contributor Address Line 1" TEXT,
	"Contributor Address Line 2" TEXT,
	"Contributor City" TEXT,
	"Contributor State" TEXT,
	"Contributor Zip Code" TEXT,
	"Description" TEXT,
	"Check Number" TEXT,
	"Transaction ID" TEXT,
	"Filed Date" DATE,
	"Election" TEXT,
	"Report Name" TEXT,
	"Start of Period" TEXT,
	"End of Period" TEXT,
	"Contributor Code" TEXT,
	"Contribution Type" TEXT,
	"Report Entity Type" TEXT,
	"Committee Name" TEXT,
	"Candidate Last Name" TEXT,
	"Candidate First Name" TEXT,
	"Candidate Middle Name" TEXT,
	"Candidate Prefix" TEXT,
	"Candidate Suffix" TEXT,
	"Amended" TEXT,
	"Contributor Employer" TEXT,
	"Contributor Occupation" TEXT,
	"Occupation Comment" TEXT,
	"Employment Information Requested" TEXT
);
