
on: deployment_status

jobs:
  associate:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'openness-project-nmid'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ github.event.deployment_status.deployment.ref }}'
          fetch-depth: 0
      - name: install sentry-cli
        run: pip install sentry-cli
      - name: Sleep to make sure that heroku deployment is really done
        run: sleep 300
        shell: bash
      - name: get release version
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo "HEROKU_RELEASE=`heroku config:get HEROKU_RELEASE_VERSION -a openness-project-nmid`-openness-project-nmid" >> "$GITHUB_ENV"
      - name: inform sentry about release
        env:
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          sentry-cli releases new -p openness-project $HEROKU_RELEASE
          sentry-cli releases set-commits $HEROKU_RELEASE
          sentry-cli releases finalize $HEROKU_RELEASE
