name: Import scraped data to configured database

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 7 * * *'   
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-workflow]
    
jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build containers and import scraped data
        # It would be awesome to be able to send the make target in the payload
        # of the triggering workflow, defaulting to "nightly" for manual runs
        run: |
          touch .env
          docker-compose -f docker-compose.etl.yml run --rm \
            -e AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            app make nightly
