name: Import scraped data to configured database

on:
  workflow_dispatch:
  repository_dispatch:
    types: [nightly-scrape-done]

jobs:
  generate_years_array:
    runs-on: ubuntu-latest
    outputs:
      years: ${{ steps.set_years.outputs.years }}
    steps:
      - name: Generate year range
        id: set_years
        run: |
          echo "years=$(python3 -c "
          import json
          from datetime import date
          current_year = date.today().year
          print(json.dumps(list(current_year - 2, current_year + 1))))
          ")" >> $GITHUB_OUTPUT

  import_filings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Import candidate, PAC, and filing data
        run: |
          touch .env
          docker compose -f docker-compose.etl.yml run --rm \
            -e AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            app make import/candidates import/pacs import/candidate_filings import/pac_filings

  import_transactions:
    runs-on: ubuntu-latest
    needs: [generate_years_array, import_filings]
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        transaction_type: [CON, EXP]
        year: ${{ fromJson(needs.generate_years_array.outputs.years) }}
        month: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Import transaction data
        run: |
          touch .env
          docker compose -f docker-compose.etl.yml run --rm \
            -e AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            app make import/${{ matrix.transaction_type }}_${{ matrix.month }}_${{ matrix.year }}
