name: CI

on:
  push:
    branches:
      - master
      - deploy
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    needs: run-linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          cp .env.example .env
      - name: Build containers and run tests
        run: docker-compose -f docker-compose.yml -f tests/docker-compose.yml run --rm app
